<style>
.firewall-options-form-table tr > td
{
	border-collapse:separate; 
	border-spacing:5em;
	padding-bottom: 1em;
}
.critical { color: #D20000; }
</style>
<?php 
$wallHelper = Mage::helper('wall');
$getIncludedFile = get_included_files(); 
$rootPath = $_SERVER['DOCUMENT_ROOT'];
$paths = $rootPath.'/lib/firewall/firewall.php';
$optionsAll = Mage::getModel('wall/options')->getCollection()->getData();
$firewalFile = ini_get('auto_prepend_file');
$autoprepend = '<b>No</b>.'; 
$autoprependimageIcon =   'error_msg_icon.gif';
$firewallDisabled = 0;
if (strpos($firewalFile,'lib/firewall/firewall.php') !== false || in_array($paths, $getIncludedFile)) {	
	$firewallDisabled = 1;
	$autoprependimageIcon =  'success_msg_icon.gif'; 
	$autoprependMsg ='';
    $autoprepend = '<b>Yes</b>.';    
} else {
	$autoprependMsg .='<p class="critical">To Enable firewall include the following line in index.php in your webroot directory <br />
					after the following line of code <br /> 
					"define(\'MAGENTO_ROOT\', getcwd());"  <br /> 
					require_once MAGENTO_ROOT.\'/lib/firewall/firewall.php\';</p> or';
	$autoprependMsg .='<p class="critical">add the below line to your php.ini / fastphp / in your vhost configuration file. <br /> 	
					auto_prepend_file '.$paths.'</p>';
	
}
$senderEmail = $wallHelper->getMageEmail();
?>
<form id="edit_form" name="edit_form" method="post" action="<?php $this->getUrl('*/*/post')?>">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<table class="firewall-options-form-table">
	<tbody>
		<tr><th><h2>General Information</h2></th></tr>
		<tr>
			<th scope="row"><?php echo $optionsAll[1]['text']; ?></th>
			<td width="20" align="left">
				<?php 
				echo '<img width="16" height="16" border="0" src="/skin/adminhtml/default/default/images/'.$autoprependimageIcon.'">'; ?>
			</td>
			<td align="left">
				<input type="hidden" name="fireWall_options[2][option_id]" value="<?php echo $optionsAll[1]['option_id']; ?>">
				<select style="width:200px" name="fireWall_options[2][value]" disabled>
					<option  value="1"> <?php echo $autoprepend; ?></option>
				</select>
				<?php if($firewallDisabled==0) { echo $autoprependMsg; } ?>
			</td>
		</tr>
		<tr>
			<th scope="row">Hacking Attempts</th>
			<td></td>
			<td align="left">
				<a href="<?php echo  Mage::helper("adminhtml")->getUrl("wall/adminhtml_logs/index"); ?>">
					<?php echo $_blockData = $wallHelper->getLogsCount(); ?>
				</a>
			</td>
		</tr>
		<tr><th><h2>Basic Configuration</h2></th></tr>
		<tr>
			<th scope="row"><?php echo $optionsAll[0]['text']; ?></th>
			<td width="20" align="left">
				<?php $imageIcon = ($optionsAll[0]['value']==1 && $firewallDisabled==1) ? 'success_msg_icon.gif' : 'error_msg_icon.gif'; 
				echo '<img width="16" height="16" border="0" src="/skin/adminhtml/default/default/images/'.$imageIcon.'">'; ?>
			</td>
			<td align="left">				
				<input type="hidden" name="fireWall_options[1][option_id]" value="<?php echo $optionsAll[0]['option_id']; ?>">
				<select style="width:200px" name="fireWall_options[1][value]" <?php echo ($firewallDisabled==0) ? "disabled" : ''; ?>>
				<?php if($firewallDisabled==1) { ?>	<option <?php echo ($optionsAll[0]['value']==1 && $firewallDisabled==1) ? 'selected=""' : ''; ?>  value="1">Enabled</option> <?php } ?>
					<option <?php echo ($optionsAll[0]['value']==0) ? 'selected=""' : ''; ?> value="0">Disabled</option>
				</select>
			</td>
		</tr>
		<tr>
			<th scope="row"><?php echo $optionsAll[2]['text']; ?></th>
			<td width="20" align="left">				
			</td>
			<td align="left">
				<input type="hidden" name="fireWall_options[3][option_id]" value="<?php echo $optionsAll[2]['option_id']; ?>">				
				<select style="width:200px" name="fireWall_options[3][value]">
					<option <?php echo ($optionsAll[2]['value']==1) ? 'selected=""' : ''; ?>  value="1">Enabled</option>
					<option <?php echo ($optionsAll[2]['value']==0) ? 'selected=""' : ''; ?> value="0">Disabled</option>
				</select>
			</td>
		</tr>
		<tr>
			<th scope="row"><?php echo $optionsAll[3]['text']; ?></th>
			<td width="20" align="left">				
			</td>
			<td align="left">					
				<input type="hidden" name="fireWall_options[4][option_id]" value="<?php echo $optionsAll[3]['option_id']; ?>">			
				<input type="text" name="fireWall_options[4][value]" value="<?php echo $optionsAll[3]['value']; ?>" />
			</td>
		</tr>
		<tr>
			<th scope="row"><?php echo $optionsAll[4]['text']; ?></th>
			<td></td>
			<td align="left">
				<input type="hidden" name="fireWall_options[5][option_id]" value="<?php echo $optionsAll[4]['option_id']; ?>">
				<input type="text" name="fireWall_options[5][value]" value="<?php echo (empty($optionsAll[4]['value'])) ? $senderEmail : $optionsAll[4]['value']; ?>" />
			</td>
		</tr>
		<?php /*<tr>
			<th scope="row"><?php echo $optionsAll[5]['text']; ?></th>
			<td></td>
			<td align="left">
				<input type="hidden" name="fireWall_options[6][option_id]" value="<?php echo $optionsAll[5]['option_id']; ?>">
				<select style="width:200px" name="fireWall_options[6][value]">
					<option <?php echo ($optionsAll[5]['value']==1) ? 'selected=""' : ''; ?>  value="1">Enabled</option>
					<option <?php echo ($optionsAll[5]['value']==0) ? 'selected=""' : ''; ?> value="0">Disabled</option>
				</select>
			</td>
		</tr> */ ?>
		<tr>
			<th scope="row"><?php echo $optionsAll[6]['text']; ?></th>
			<td></td>
			<td align="left">
				
				<input type="hidden" name="fireWall_options[7][option_id]" value="<?php echo $optionsAll[6]['option_id']; ?>">
				<input type="text" name="fireWall_options[7][value]" value="<?php echo $optionsAll[6]['value']; ?>" />
			</td>
		</tr>
		<tr>
			<th scope="row"><?php echo $optionsAll[7]['text']; ?></th>
			<td></td>
			<td align="left">				
				<input type="hidden" name="fireWall_options[8][option_id]" value="<?php echo $optionsAll[7]['option_id']; ?>"><select style="width:200px" name="fireWall_options[8][value]">
					<option <?php echo ($optionsAll[7]['value']==1) ? 'selected=""' : ''; ?>  value="1">Enabled</option>
					<option <?php echo ($optionsAll[7]['value']==0) ? 'selected=""' : ''; ?> value="0">Disabled</option>
				</select>
			</td>
		</tr>
	</tbody>
</table>
<?php //echo $this->__($message) ?>
<br>
<br>
<button style="" onclick="firewallConfigForm.submit()" class="form-button" type="button" title="Save Config" id=""><span><span><span><?php echo $this->__('Save Configuration') ?></span></span></span></button>
    </form>
    <br>
    <br>
<?php //echo $this->__('MageFirewall configuration : '.$autoprepend) ?>
<br>
<?php //echo $autoprependMsg; ?>
<script type="text/javascript">
    var firewallConfigForm = new varienForm('edit_form');
</script>
