<iframe style="display:none; border: medium none;" id="iframess" src="" width="100%" height="700px"></iframe>
<script>
	var url = "<?php echo Mage::helper('adminhtml')->getUrl('wall/adminhtml_dashboard_View') ?>";
	var baseUrl = "<?php echo Mage::getBaseUrl(); ?>";
	var r = confirm("Press ok to scan you store. This may not work under intranet environment");
	var iframe = document.getElementById('iframess');
	if (r == true) {
		iframe.src = 'http://magefirewall.com/scan.php?url='+baseUrl;
		iframe.show();
	} else {
		window.location = url;
	}	
</script>
